version: 2

jobs:
   build:
     docker:
       - image: circleci/openjdk:9
     steps:
       - checkout
       - restore_cache:
           key: dependency-cache-{{ checksum "build.gradle" }}
       - run:
           command: ./gradlew clean build
       - run:
           command: ./gradlew bintrayUpload -Prelease
       - save_cache:
           key: dependency-cache-{{ checksum "build.gradle" }}
           paths:
             - ~/.gradle
       - run:
           command: mkdir ~/test-results
       - run:
           command: find ~ -type f -regex ".*/test-results/.*xml" -exec ln {} ~/test-results/ \;
       - store_test_results:
           path: ~/test-results
       - store_artifacts:
           path: ~/test-results
       - store_artifacts:
           path: build/libs